stages:
  - test
  - build

lint:dockerfile:
  stage: test
  image: hadolint/hadolint:v1.19.0-alpine
  script:
    - find . -type f -name "Dockerfile*" -print0 | xargs -0 -n1 hadolint

build:base:
  stage: test
  image: 
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  script:
    - >
      /kaniko/executor
      --context ./base
      --dockerfile ./base/Dockerfile
      --build-arg VERSION="3.8.0"
      --no-push

build:crystal:
  stage: test
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  script:
    - >
      /kaniko/executor
      --context ./crystal
      --dockerfile ./crystal
      --build-arg VERSION="3.8.0"
      --no-push
  needs:
    - build:base

build:perl:
  stage: test
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  script:
    - >
      /kaniko/executor
      --context ./perl
      --dockerfile ./perl
      --build-arg VERSION="3.8.0"
      --no-push
  needs:
    - build:base