version: "2.2"

services:
  alpine:
    image: kodelib/code-server:${VERSION}-r${REVISION}-alpine
    build:
      context: ./variants/alpine
      args: 
        VERSION: ${VERSION}
    command:
      - --host=0.0.0.0
    ports:
      - 8080:8080
    environment:
      PASSWORD: 1234567890