versio: "1.0"

variables:
  VERSION: "3.8.0"

jobs:
  main:
    description: Run code-server locally
    commands:
      - >
        docker run --rm 
        --publish 8080:8080 
        --env PASSWORD=1234567890 
        kodelib/code-server-crystal:${VERSION}

  lint:
    description: Check all Docker files
    commands:
      - hadolint --version
      - find . -type f -name "Dockerfile*" -print0 | xargs -0 -n1 hadolint

  build:
    description: Build all image variants
    commands:
      - docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}" "kodelib/code-server*:${VERSION}"
    needs:
      - build:crystal
      - build:perl

  build:base:
    description: Build base image
    variables:
      IMAGE_NAME: kodelib/code-server
    commands:
      - >
        docker build .
        --build-arg VERSION="${VERSION}"
        --tag "${IMAGE_NAME}:${VERSION}"

  build:crystal:
    variables:
      IMAGE_NAME: kodelib/code-server-crystal
    commands:
      - >
        docker build ./variants/crystal
        --build-arg VERSION="${VERSION}"
        --tag "${IMAGE_NAME}:${VERSION}"
    needs:
      - build:base

  build:perl:
    variables:
      IMAGE_NAME: kodelib/code-server-perl
    commands:
      - >
        docker build ./variants/perl
        --build-arg VERSION="${VERSION}"
        --tag "${IMAGE_NAME}:${VERSION}"
    needs:
      - build:base

  push:
    description: Push images to Docker Registry
    commands:
      - docker push kodelib/code-server:$VERSION
      - docker push kodelib/code-server-crystal:$VERSION
      - docker push kodelib/code-server-perl:$VERSION
