version: "1.0"

variables:
  IMAGE_NAME: "kodelib/code-server"
  VERSION: "3.8.0"
  REVISION: "0"

jobs:
  lint:
    description: Check all Docker files
    commands:
      - hadolint --version
      - find . -type f -name "Dockerfile*" -print0 | xargs -0 -n1 hadolint