name: CD

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Quality
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          curl -sL https://github.com/hadolint/hadolint/releases/download/v1.22.1/hadolint-Linux-x86_64 -o hadolint && chmod a+x hadolint
          find . -type f -name "Dockerfile*" -print0 | xargs -0 -n1 ./hadolint

      - name: Build images
        run: |
          docker-compose build

      - name: Publish images
        run: |
          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker-compose push
