name: CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install prerequisites
        env:
          WERK_URL: https://github.com/marghidanu/werk/releases/download/0.1.11/werk-ubuntu-18.04
        run: |
          sudo curl -sL "${WERK_URL}" -o /usr/local/bin/werk
          sudo chmod a+x /usr/local/bin/werk
      
      - name: Quality
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          brew install hadolint
          werk run lint

      - name: Build images
        run: |
          werk run build

      - name: Publish images
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          werk run publish